<?php

namespace App\Enums\api\v1;

enum ERROR_TYPE: string
{
    case HTTP_UNPROCESSABLE_ENTITY = 'UNPROCESSABLE_ENTITY';
    case HTTP_NOT_FOUND = 'NOT_FOUND';
    case HTTP_MODEL_NOT_FOUND = 'MODEL_NOT_FOUND';
    case HTTP_INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR';
    case HTTP_UNAUTHORIZED = 'UNAUTHORIZED';
}
